server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mariadb://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:3307}/${MYSQL_DATABASE:db_auth}
    username: ${MYSQL_USER:hotel_user}
    password: ${MYSQL_PASSWORD:hotel_pass}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
